### ISSUE TITLE
Compatibility issues with Markdown 2.5

### ISSUE THREAD

**Issue by cmacmackin** [FND/markdown-checklist#6]
I've found that this extension does not work with the latest version of Markdown. This first came to my attention when I was trying to use it within one of my own projects, but I've reproduced this error when using Markdown from the command line as well:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
┌─chris@hex ~/Code/ford 
└─╼ $ python -m markdown --version                                            ⏎
__main__.py 2.5.2
┌─chris@hex ~/Code/ford 
└─╼ $ python -m markdown -x markdown_checklist.extension example-project-file.md
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/markdown/__main__.py", line 111, in <module>
    run()
  File "/usr/local/lib/python2.7/dist-packages/markdown/__main__.py", line 105, in run
    markdown.markdownFromFile(**options)
  File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 496, in markdownFromFile
    md = Markdown(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 154, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 180, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 265, in build_extension
    return module.makeExtension(**configs)
  File "/usr/local/lib/python2.7/dist-packages/markdown_checklist/extension.py", line 9, in makeExtension
    return ChecklistExtension(configs=configs)
  File "/usr/local/lib/python2.7/dist-packages/markdown/extensions/__init__.py", line 36, in __init__
    self.setConfigs(kwargs.pop('configs', {}))
  File "/usr/local/lib/python2.7/dist-packages/markdown/extensions/__init__.py", line 75, in setConfigs
    for key, value in items:
TypeError: 'NoneType' object is not iterable
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I've had similar issues with my own Markdown plugin ([markdown-include](https://github.com/cmacmackin/markdown-include)), so you can take a look at my code to see how I resolved it.

**Comment by FND** [comment]
Thanks for reporting this! I've just uploaded a new version with the fix - please let me know if you run into any further issues.

**Comment by cmacmackin** [comment]
Thanks! It seems to work perfectly now.

**Comment by FND** [comment]
Cool - I wasn't aware that anyone actually used this extension, so should probably introduce more bugs to provoke complaints...

**Comment by szaghi** [comment]
I am also using this extension in [MaTiSSe.py](https://github.com/szaghi/MaTiSSe).

The citing to your great extension can be found [here](https://github.com/szaghi/MaTiSSe/wiki/Requirements). I apologize myself to not let you aware before.

Thank you for great work.

**Comment by FND** [comment]
Nice, thanks for letting me know!

MaTiSSe looks like an interesting project - I'll definitely take a closer look, just might have use for it myself.
